import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Sidebar } from '@/components/sidebar'
import { Bars } from '@/components/bars/bars'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Algorithms</title>
        <meta name="Showcase of mmany algorithms" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className='bg-gray-800 min-h-screen flex justify-center items-center'>
        <Sidebar/>

        <section className='flex-col'>
          <Bars/>
        </section>
      </main>
    </>
  )
}
